### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by HelloMokuzai** [jetstream0/GoBanMe#5]
Hi Prussia, looking forward to giving this extension a trial!

I don't want to intrude but just suggesting an alternative icon - Just a quick crude mash up.

Let me know your thoughts,
MKZI
 
![gobanme](https://user-images.githubusercontent.com/53551441/129137273-133a4056-408e-4768-9abd-a5125ac61095.png)

**Comment by stjet** [comment]
Oh wow, sorry didn't see this until now. I love the icon (thanks for making it!). However, I can see one potential problem. Because these icons are going to be a tiny tiny, icons in the browser extension bar so it may have too much resemblance to the actual banano logo which isn't too big of a deal, but, I anticipate other banano related browser extension projects will use the banano logo or similar designs for their extensions, and I don't want it to be confusing if many of them are installed.

**Comment by HelloMokuzai** [comment]
Good point - having a logo that differentiates your project from other BANANO related extensions but is still easily identifiable would be ideal.

No worries. Looking forward to trialling your extension!

**Comment by stjet** [comment]
Hi! You can already the download the extension on the firefox web browser here: https://addons.mozilla.org/en-US/firefox/addon/gobanme/

**Comment by HelloMokuzai** [comment]
Thanks. I'm using Brave currently so will wait for the Chromium based release.

**Comment by stjet** [comment]
Hello! The chromium version is now released: https://prussia.dev/to/gobanme-chrome
